main:
  push:
    - stages:
        - name: deploy-to-pages
          image: alpine:latest
          script:
            - echo ">>> 检测到纯静态项目，跳过构建，直接部署"
            - mkdir -p /tmp/deploy
            # 确保路径与你仓库里的实际文件夹完全一致
            - cp -r deploy-pkg/liwang-jiankong/* /tmp/deploy/
            - ls -la /tmp/deploy
          artifacts:
            path: /tmp/deploy