"""Inspect actual modal content for算电协同 to see if SWOT 4-section is shown."""
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    browser = pw.chromium.launch(headless=True)
    ctx = browser.new_context(viewport={"width": 1920, "height": 1080})
    page = ctx.new_page()
    page.goto("http://localhost:8080/", wait_until="networkidle", timeout=15000)
    page.fill("#gate-input", "nsp2026")
    page.click(".gate-box button")
    page.wait_for_selector(".tab-btn", timeout=5000)
    page.wait_for_timeout(300)
    page.click("[data-view='view-5']")
    page.wait_for_timeout(500)
    # Click算电协同 card (index 7)
    cards = page.locator(".m5card")
    cards.nth(7).scroll_into_view_if_needed()
    cards.nth(7).click()
    page.wait_for_selector(".modal-mask.show", timeout=3000)
    page.wait_for_timeout(300)
    html = page.locator("#modal-content").inner_text()
    print("===== MODAL CONTENT (text only) =====")
    print(html)
    print("===== END =====")
    browser.close()